# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atuadores.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'atuadores.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61tuadores.proto\x12\tatuadores\"\x0e\n\x0c\x43omandoVazio\"#\n\x0fRespostaAtuador\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\x1f\n\rEstadoAtuador\x12\x0e\n\x06ligado\x18\x01 \x01(\x08\")\n\x12TemperaturaAtuador\x12\x13\n\x0btemperatura\x18\x01 \x01(\x01\"?\n\x18\x45stadoTemperaturaAtuador\x12\x0e\n\x06ligado\x18\x01 \x01(\x08\x12\x13\n\x0btemperatura\x18\x02 \x01(\x01\x32\xc8\x02\n\x0e\x41rCondicionado\x12J\n\x13LigarArCondicionado\x12\x17.atuadores.ComandoVazio\x1a\x1a.atuadores.RespostaAtuador\x12M\n\x16\x44\x65sligarArCondicionado\x12\x17.atuadores.ComandoVazio\x1a\x1a.atuadores.RespostaAtuador\x12K\n\x0eSetTemperatura\x12\x1d.atuadores.TemperaturaAtuador\x1a\x1a.atuadores.RespostaAtuador\x12N\n\x0eGetTemperatura\x12\x17.atuadores.ComandoVazio\x1a#.atuadores.EstadoTemperaturaAtuador2\xdd\x01\n\x07Lampada\x12\x43\n\x0cLigarLampada\x12\x17.atuadores.ComandoVazio\x1a\x1a.atuadores.RespostaAtuador\x12\x46\n\x0f\x44\x65sligarLampada\x12\x17.atuadores.ComandoVazio\x1a\x1a.atuadores.RespostaAtuador\x12\x45\n\x10GetEstadoLampada\x12\x17.atuadores.ComandoVazio\x1a\x18.atuadores.EstadoAtuador2\x83\x02\n\x10\x43ontroleIncendio\x12M\n\x16\x41tivarControleIncendio\x12\x17.atuadores.ComandoVazio\x1a\x1a.atuadores.RespostaAtuador\x12P\n\x19\x44\x65sativarControleIncendio\x12\x17.atuadores.ComandoVazio\x1a\x1a.atuadores.RespostaAtuador\x12N\n\x19GetEstadoControleIncendio\x12\x17.atuadores.ComandoVazio\x1a\x18.atuadores.EstadoAtuadorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atuadores_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMANDOVAZIO']._serialized_start=30
  _globals['_COMANDOVAZIO']._serialized_end=44
  _globals['_RESPOSTAATUADOR']._serialized_start=46
  _globals['_RESPOSTAATUADOR']._serialized_end=81
  _globals['_ESTADOATUADOR']._serialized_start=83
  _globals['_ESTADOATUADOR']._serialized_end=114
  _globals['_TEMPERATURAATUADOR']._serialized_start=116
  _globals['_TEMPERATURAATUADOR']._serialized_end=157
  _globals['_ESTADOTEMPERATURAATUADOR']._serialized_start=159
  _globals['_ESTADOTEMPERATURAATUADOR']._serialized_end=222
  _globals['_ARCONDICIONADO']._serialized_start=225
  _globals['_ARCONDICIONADO']._serialized_end=553
  _globals['_LAMPADA']._serialized_start=556
  _globals['_LAMPADA']._serialized_end=777
  _globals['_CONTROLEINCENDIO']._serialized_start=780
  _globals['_CONTROLEINCENDIO']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
